### ISSUE TITLE
Problems with PDF customizations being taken into account when using Saxon 9.8.0.12

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3156]
Two of our clients complained that when using the stock DITA OT 3.2 sometimes their XSLT customizations are no longer taken into account, latest report is here:

https://www.oxygenxml.com/forum/topic17977.html

Basically if their "custom.xsl" imports a "front-matter.xsl" placed relative to it, Saxon somehow skips over this import and uses the "front-matter.xsl" specified in the base PDF folder.

I have a plugin with which I can reproduce the problem on my side, with Saxon 9.1 the problem with the XSLT imports precedence cannot be reproduced but unfortunately I'm having trouble putting together a small XML + XSLT package to open an issue on the Saxonica list.
My first idea would be to update to Saxon 9.9 and see if the problem is fixed, unfortunately the DITA OT 3.2 Java code needs to be updated in order to work with Saxon 9.9:

      Error: java.lang.NoSuchMethodError: net.sf.saxon.Controller.setMessageEmitter(Lnet/sf/saxon/event/Receiver;)V

**Comment by robander** [comment]
If this is the same problem I ran into in DITA-OT 3.0 / 3.1, then the workaround is to use an explicit `plugin:` style reference in the import. For example instead of
`<xsl:import href="front-matter.xsl"/>`
use 
`<xsl:import href="plugin:org.example.my.plugin.id:xsl/fo/front-matter.xsl"/>`

I worked around this in 3.0 by putting that kind of path in one of the files we ship: https://github.com/dita-ot/dita-ot/pull/2892

**Comment by jelovirt** [comment]
Should we change the stylesheets in 3.2.1 by changing all relative import URIs to (absolute) `plugin` URIs?

**Comment by robander** [comment]
@jelovirt that would probably be a good idea - and might encourage others to use it (making it easier to move XSL around in the future).

**Comment by jelovirt** [comment]
Also, it would make it easier to fork a shell stylesheet for e.g. PDF2.

**Comment by infotexture** [comment]
:+1: We already recommend this approach in the docs under [Plug-in coding conventions](https://www.dita-ot.org/dev/topics/plugin-coding-conventions.html)

**Comment by raducoravu** [comment]
I will find time to look more into this on my side, see for example if using the plugin-style uri imports in the base pdf plugin xslts fixes the problem or not.

**Comment by robander** [comment]
@jelovirt do you want me to try that update for 3.2.1? Not sure if it overlaps with your work in #3157 (don't think I see that change in 3157 though).

**Comment by jelovirt** [comment]
@robander I started this PR already

**Comment by jelovirt** [comment]
The branch is https://github.com/dita-ot/dita-ot/tree/feature/absolute_xslt_import. Do you want to continue from that? I think there are some typos there.

**Comment by robander** [comment]
Sure, I'll take a look at it, probably tonight. And yes, I was picturing the merge conflicts this will create between the hotfix + develop...

**Comment by jelovirt** [comment]
https://github.com/dita-ot/dita-ot/pull/3159 has been merged to `hotfix/3.2.1`. @raducoravu are you able to test this with that change?

**Comment by raducoravu** [comment]
@jelovirt good work, I confirm I can no longer reproduce the end user's problem using a 3.2.1 build.
