### ISSUE TITLE
Embedded SVGs in PDF no longer work with DITA OT 3.4

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3414]
This was reported here:
https://www.oxygenxml.com/forum/viewtopic.php?f=20&t=20907

       dita-ot-3.4_test\plugins\org.dita.pdf2.fop\build_fop.xml:145: java.lang.NoClassDefFoundError: org/w3c/dom/svg/SVGDocument

From the "org.dita.pdf2.fop/lib" folder the "xml-apis-ext-1.3.04.jar" library is missing and according to the end user this seems to cause the problem.

**Comment by infotexture** [comment]
💥 Verified in 3.4 distribution docs PDF: 

The [processing-flow.svg](https://github.com/dita-ot/docs/blob/develop/reference/images/processing-flow.svg) image used to illustrate the [processing structure](https://www.dita-ot.org/dev/reference/processing-structure.html) is missing from the topic entirely.

We'll need to check the logs to see whether any related messages are issued, but builds succeed regardless — which explains why the error went unnoticed during the release process.

**Comment by raducoravu** [comment]
+1, someone else reported the same problem on an Oxygen support email address.

**Comment by raducoravu** [comment]
@infotexture looking in the DITA OT 3.4.1 zip, I still cannot see there the "org.dita.pdf2.fop/lib/xml-apis-ext-1.3.04.jar" JAR library.

**Comment by infotexture** [comment]
@raducoravu That's odd. When I unpack the [3.4.1 release package](https://github.com/dita-ot/dita-ot/releases/download/3.4.1/dita-ot-3.4.1.zip), I see it in the expected location: `plugins/org.dita.pdf2.fop/lib/xml-apis-ext-1.3.04.jar`. 🤔

**Comment by raducoravu** [comment]
Oh, alright then. Thanks, I was looking for it in the main "lib" folder.
