### PR TITLE
Use absolute URIs in XSLT imports and includes

### LINKED ISSUE #3156: Problems with PDF customizations being taken into account when using Saxon 9.8.0.12
Two of our clients complained that when using the stock DITA OT 3.2 sometimes their XSLT customizations are no longer taken into account, latest report is here:

https://www.oxygenxml.com/forum/topic17977.html

Basically if their "custom.xsl" imports a "front-matter.xsl" placed relative to it, Saxon somehow skips over this import and uses the "front-matter.xsl" specified in the base PDF folder.

I have a plugin with which I can reproduce the problem on my side, with Saxon 9.1 the problem with the XSLT imports precedence cannot be reproduced but unfortunately I'm having trouble putting together a small XML + XSLT package to open an issue on the Saxonica list.
My first idea would be to update to Saxon 9.9 and see if the problem is fixed, unfortunately the DITA OT 3.2 Java code needs to be updated in order to work with Saxon 9.9:

      Error: java.lang.NoSuchMethodError: net.sf.saxon.Controller.setMessageEmitter(Lnet/sf/saxon/event/Receiver;)V

### PR DESCRIPTION
**Pull request by jelovirt**
Use absolute `plugin` URIs in XSLT imports and includes, even in cases where a relative URI inside a plugin could be used.

Possibly fixes #3156

### CODE REVIEW

**Comment by jelovirt** [comment]
@robander IMO we don't need to verify if this fixes the Saxon bug. I think this is a change we want, regardless of Saxon.

**Comment by robander** [comment]
@jelovirt agreed -- it's a good change either way.
