### ISSUE TITLE
Dita-OT 3.1 plugin integration does not work correctly

### ISSUE THREAD

**Issue by hscherzer** [dita-ot/dita-ot#3006]
## Expected Behavior
Using the **integrator.xml** mechanism (as always) a plugin should correctly be added to the DITA-OT3

## Actual Behavior
Several indications show that something is wrong, here are the observations
1.  "call ant -f integrator.xml" works without errors (good)
2.  Processing a simple .ditamap generates the log ... T:\Dita-OT3\plugins\org.dita.pdf2\xsl\fo\bookmarks.xsl:42:31: Warning! Stylesheet module bookmarks.xsl is included or imported more than once.

    This should not be warned about, but it is not crucial for the misbehavior. HOWEVER - the following is
3. Logfile:

    ```
    T:\Dita-OT3\plugins\org.dita-community.xpower\cfg\fo\xsl\back-matter.xsl:49:8: Fatal Error! **Variable pubDate has not been declared (or its declaration is not in scope)**
    ```
    ```
    T:\Dita-OT3\plugins\org.dita-community.xpower\cfg\fo\xsl\equations.xsl:112:57: Fatal Error! **Cannot find a template named getChapterPrefix**
    ```
Both messages show that variables and templates that are implemented in different files (of the plugin) are **no more  found** by the statements that call/use them. This is all working with Version 3.0.3 but when going to 3.1 those problems started.

I have done more than 20 integrations, always following the latest version, so I don't believe that I'm doing a typical beginner's fault.

## Possible Solution
1. Optional: Please remove the above warnings - it should be well possible to have the same name to override, people who write plugins may be expected to know what they do. Perhaps that warning could be made conditional according to the 'panic-level'.

2. IMPORTANT: please check the plugin-integration. There are even more effects but I assume they all base on the same problem.

I provided a full example running right from the batch file "runFile.bat" to create the problem. Even the class path is set correctly in ant.bat.

## Steps to Reproduce
Please contact me helmut.scherzer@gi-de.com with an e-mail so I can assign you a link to a share server that holds the sample package. It is 60 MB large and I do not see any repository that would allow that exchange but I have one on my side that needs to be assigned to particular receiver (e-mail addr).

Then ...run "runFile.bat" (Windows) on any T: drive that you can create with something like "subst T: F:\myDownload"

The result will be a log file that indicates the problem (search "Fatal")

## Environment
The environment will be mostly set with runFile.bat, java path etc. should be locally there.

* DITA-OT version: 3.1
* Operating system and version:
Windows 7 Professional
* How did you run DITA-OT?
See example using ant
* Transformation type:
xpower (runFile.bat does it already)

**Comment by raducoravu** [comment]
Maybe you should try to create a small cut-down sample DITA OT plugin exemplifying the problem and attach it to the opened issue. I'm sorry but I'm not sure that I have the time to go through 60MBs of XSLT customizations.

**Comment by hscherzer** [comment]
Dear Radu,

I do understand very well. Yet ... 80% of the 60MB is made from the .\lib directories because I delivered a full DITA-OT. That's for good reason, because regarding "time", it takes just as long as to unZIP the package to a drive T:\ and to run the "runFiles.bat".

That should be around 60 seconds to do. Then you would see the error in the log file. I am sure that someone of the team knows a.) where the warnings are generated ("... same name ...") and b.) also what could be the reason that the plug-in files are not integrated such that they may distribute definitions and access to variables or templates.

Actually I can do very much myself and I'm willing to ... so perhaps it would be enough if I understood "what happens with integrate.xml" because I am not yet able to compile (and debug) the dost.jar. As dost-config.jar is generated something there must be the secrect.

My hope was not that you'd fix my implementation .. but maybe to get a clue where I should start investigation. Thanks for caring .. pls invest the 60 seconds thing and just get an impression ... some tips will be enough. Thanks for caring

**Comment by robander** [comment]
The "Stylesheet is included more than once" message comes from Saxon, and is not something we can change. We finally upgraded the version of Saxon we ship a few months ago (after using the same version for many years), and this message is part of the new module. It's not something we can change (and for me, it has been helpful to track down some precedence issues when I did not intend to import a file twice). As long as you really are importing twice, the message can be ignored, as you said. (I ran into a Windows-only issue where the wrong file was picked up because two files had the same name -- you can see that [here](https://github.com/dita-ot/dita-ot/pull/2892), along with the fix of using `plugin:` syntax on imports).

A couple things to try...

1. Does this happen on all maps when you use the `xpower` transformation type? For errors like the one you see, I would expect to get the error with any source file, even simple ones like `docsrc/samples/hierarchy.ditamap`.
1. If it happens on any map, what happens if you use the `dita` command instead of an Ant file? For example:
`dita-ot-3.1\bin\dita -i input.ditamap -f xpower`
1. Does this also happen with other PDF transformations? What happens if you just try to use `pdf` as the transformation type?

**Comment by hscherzer** [comment]
Dear Rob, thanks very much for the helpful reflections. Let me first answer your questions:

1. "on all maps"? ... The `already there` warning works already with one overridden file (e.g. bookmarks.xsl) and I do understand the idea of Saxon. The `variable not found problem` I'm currently trying to reduce to a minimized customization.
2. I will try the dita invokation and let you know the results.
3. The `variable not found` problem does not occur when running pdf2 transformation. I'm not so surprised because all what we see seems to have to do with plugin-integration and pure pdf2 is not a customization.

**My careful observation:** Indeed the entire thing smells like having to do with the Saxon lib. I have to use an SaxonEE version because I'm using calls to Java in `svgSize.xsl` to determine the size of an image for auto-aligning its width/height to page or textflow. 

I can do this another way like I do with .SVG, so I could fall back to the HE version that is delivered. But for the oxygen-highlight plugin getVersion (part of HE) has to be called too, which did also no more work since 3.1. Using the 3.1 with the **original distribution SaxonHE** gave me `function not found` on trying to call `getVersion()`. Can be tested when you try to add the `com.oxygenxml.highlight` plugin.

When playing with `SaxonEE` (replacing the default HE) I had some clashes first. Because I had forgotten to put the license file to the lib directory, the EE automatically falls back to HE and gave me the `function not found`. Adding the license file (EE-level) solved the problem. So maybe they started to be more restrictive in HE using some functions?

I also wonder what's being used to compile `dost.jar` (from the source) - maybe there's a mismatch. Trying to simply copy the Saxon `saxon-9.1.0.8.jar` from version 3.0.3 would generate many such errors in the `integrate.xml`, so there must be something in the system that "knows" about another version being used for **what?**

Summarizing ... I will come back with the rest of the answers and **question** ... 

> Could there be any dependency between the compilation environment of `dost.jar` with respect to the plugin-integration (where `dost-configuration.jar` is made) ?

I think if I only would know a bit better about the process (from compiling the java source until plugin-interation) I could deploy my full personal power of debugging and understanding what's happening.

Thanks again for your highly appreciated help.

**Comment by hscherzer** [comment]
uups

**Comment by raducoravu** [comment]
I downloaded your samples and looked over them. You seem to have a modified DITA OT distribution plus probably most of the XSLT stylesheets from the PDF publishing have been overwritten in your PDF customization plugin.
Logging in what problems I found:

Your "runFile.bat" assumes that the DITA OT is placed in "T:\Dita-OT3". This is not my case, so I had to rewrite quite a lot of paths in the bat file. 
After first running "runFile.bat" I got the problem you reported.
The problem is that the XSLT stylesheet "Dita-OT3\plugins\org.dita-community.xpower\cfg\fo\xsl\pr-domain.xsl" is not wellformed. I cannot blame you for not noticing this because indeed Saxon 9.8 seems to complain of a lot of things, but they all stem from this problem of one of the XSLT stylesheets not being wellformed (problem which is not individually reported). I had to switch to using Saxon 9.1 in order to understand the problem as Saxon 9.1 actually reports the XSLT as not being wellformed.

**Comment by hscherzer** [comment]
Thanks VERY MUCH for your helpful investigation. I will check for your observation and I am grateful for your detailed experiments with Saxon. A remark - I thought I had indicated: In Windows ... if you issue   

`C:\MyWhateverdir>subst T: C:\MyWork\Issue3006`

will give you a perfect `T:`  drive containing everything that you have on `C:\MyWork\Issue3006` until you launch  `subst T: /d`
That way you can always create the 'other' environment. Again thanks very much for caring !

**Comment by raducoravu** [comment]
@hscherzer Oh, ok, did not read this carefully and did not see the **subst** suggestion.

**Comment by hscherzer** [comment]
I just scrutinized the "not well formed" and oxygen editor does not give me any hint but the idea that 
`$side-col-width` is not in scope (as I'm not using master file). However, that variable is correctly defined in `basic-settings.xsl` which lives in the same `cfg/fo/attrs` directory. Indeed "not finding those variables" seems to be a problem that might relate to Saxon 9.8.
```
        <xsl:attribute name="start-indent">
            <xsl:value-of select="$side-col-width"/>
        </xsl:attribute>
```
I will try to play with Saxon 9.1 to get the same reference as you have. Currently still a bit hard to understand what's the real problem. I don't want to annoy with the "never satisfied comment", so I will come back with some more investigations after your precious remarks and hints above.

**Comment by raducoravu** [comment]
@hscherzer Just downloaded the ZIP again just to be sure.
So if you download the ZIP and open from it the XSLT "Dita-OT3\plugins\org.dita-community.xpower\cfg\fo\xsl\pr-domain.xsl" and then use Oxygen's "Validate" toolbar button it should present an error like:

          org.xml.sax.SAXParseException; systemId:          ..../Dita-OT3/plugins/org.dita-community.xpower/cfg/fo/xsl/pr-domain.xsl;            lineNumber: 278; columnNumber: 11; The element type "xsl:when" must            be terminated by the matching end-tag "</xsl:when>".

**Comment by hscherzer** [comment]
Ouuch - now found it (I mixed it up with attrs, but it is in xsl. I will fix and come back) - feeling ashamed that you' need to fix such of my bugs.

**Comment by hscherzer** [comment]
I fixed the `pr-domain.xsl` and visited all `.xsl` in the xpower-plugin to avoid any further bug. The updated files are in
[https://idgard.itsmyprivacy.de/s?b=177ihkjtirbft650tvo787f3ff6ifdbqgneby9m79kp7r2tpvd](url)
and will give the new package `runFile2.zip` which can be run instantly (runFile.bat) with the T: Drive trick
`C:\>subst T: C:\myWorkDir`

The remaining problem is the "variable not found" - as shown in (in `logahf.txt`) Line 419
`org.dita-community.xpower\cfg\fo\xsl\back-matter.xsl:18:9: Fatal Error! Variable copyYear has not been declared`

where **copyYear** is **declared** in `...\org.dita-community.xpower\cfg\fo\xsl\root-processing.xsl` 

```
225:<xsl:variable name="copyYear">
        ....
240:</xsl:variable>
```
**used** in `...\org.dita-community.xpower\cfg\fo\xsl\back-matter.xsl`

```
16:       <fo:block xsl:use-attribute-sets="__backmatter__copyright">
17:         <xsl:text>Copyright &#169;</xsl:text>
18:         <xsl:value-of select="$copyYear"/><xsl:text> </xsl:text>
19:       </fo:block>
```

and **integrated** by `...\org.dita-community.xpower\cfg\fo\xsl\custom.xsl`
```
     ....
 9: <xsl:import href="root-processing.xsl"/>
10: <xsl:import href="root-processing_axf.xsl"/>
11: <xsl:import href="static-content.xsl"/>
12  <xsl:import href="lists.xsl"/>
13: <xsl:import href="tables.xsl"/>
14: <xsl:import href="front-matter.xsl"/>
15: <xsl:import href="back-matter.xsl"/>
     ....
```
The import statements make it obvious the `back-matter.xsl` is imported correctly same as ` root-processing.xsl` and the declaration should be found.

Trying to play with `saxon-9.1.0.8.jar / saxon-9.1.0.8-dom.jar` by copying them to `Dita-OT\lib` (of course removing Saxon 9.8) did not work because for some strange reason I'm getting 
`org.dita.base\build_preprocess2.xml:143: java.lang.NoClassDefFoundError: net/sf/saxon/jaxp/TransformerImpl`
which is fair because it is not contained in 9.1.0.8. But I don't know what to do that `TransformerImpl `is searched in the proper 9.1.0.8 class (under `java `not `jaxp`)

Running a` un-zip` and `runFile.bat` would be enough simply in order to check whether we can produce the same problem. If yes ... good .. I would continue to investigate - maybe a short hint will help how to involve 9.1.0.8 rather than 9.8xx - something must be recompiled to avoid seeking `TransformerImpl `in `jaxp`. Thanks again for caring !

**Comment by raducoravu** [comment]
@hscherzer I will have another look when I have the time. To make DITA OT 3.1 work with Saxon 9.1 (and it does not work anymore), there is a JAR library here:

https://github.com/oxygenxml/dita-ot-3x-plugin/blob/master/dita-ot-3.x/plugins/com.oxygenxml.dost.patches/lib/oxygen-dost-patches.jar

You need to download it and in the "runFile.bat" add a reference to it in your "CLASSPATH" making sure it's the first reference in the "CLASSPATH".

**Comment by hscherzer** [comment]
Great help ! - Please do not work until I confirm next steps. The move to 9.1.0.8 reveals several bugs in pr-domain.xsl (yes, there were many changes) but they all didn't show up with 9.8. I will first fix all those bugs and come back with info what's missing (if at all). THANKS !!!!

**Comment by hscherzer** [comment]
Finally **Solved** - the application of `oxygen-dost-patches.jar` to run `saxon 9.1.0.8` was the key to get everything sorted out.

1. Using **9.1.0.8** the **correct error messages are generated** if something's wrong with the code whether "well formatted" or any wrong programming. They didn't show with saxon 9.8.x.x
2. All these odd errors above (variable not found etc.) **disappear when using saxon 9.1.0.8**.
3. That way it was possible to fix several other bugs that had been in the stylesheets (from plugin migration to 3.1) 
4. Finally the process is working - some minor fixes left to be done in pr-domain.xsl but now convergence is safe.

This is not yet the very end of the story because it remains open **what to do with Saxon 9.8.x.x** but to survive, the present solution is acceptable. **So the real problem was the migration to Saxon 9.8**.

@radu: Thanks again for the steady support, if I can be of any help sometime ... I would want to put in my 5c.

**Comment by raducoravu** [comment]
@hscherzer So after you made XSLT changes and have things work with Saxon 9.1, if you switch to Saxon 9.8 you still get some XSLT-related problems reported, right? Then indeed this could indicate a problem in the Saxon 9.8 processor but somehow in order to report the problem I would need some way of trimming down the customization plugin and your customizations are quite extensive.

**Comment by hscherzer** [comment]
@raducoravu: Indeed I'm getting through until PDF using 9.1 without errors ! Using 9.8 ALL ERRORS are still there (variable not found / template not found) exactly as reported in the beginning. So even the prior bugs did not prevent Saxon 9.8 from failing to resolve.

And yes ... stripping down the plugin for test purposes is a very important thing which I will do just in order to let us follow up the problems. I already did this once but had been so very rude (only 2 files overriding) that everything worked. I need to iterate to catch the remaining Saxon 9.8 problem. When I come done to minimum, I'll come back to let use check the reason. Will also take some days...

**Comment by raducoravu** [comment]
@hscherzer  Ideally you would end up with a small PDF customization plugin and the problem could be reproduced by plain running the "dita" command from the console view, without needing that ".bat" file to set up a classpath.
